<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css(array(
    $this->assetTheme('css/front.css'),
    //$this->assetTheme('css/animate.min.css'),
));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);

// Load google font
//$this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Raleway:400,600,700|Dancing+Script:400,700');
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
<header class="pi-header">
    <div class="pi-header-top">
        <div class="container">
            <div class="row">
                <div class="col-md-3 pi-header-logo">
                    <?php if ($module == 'system') { ?>
                        <h1>
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                            </a>
                        </h1>
                    <?php } else { ?>
                        <h2>
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                            </a>
                        </h2>
                    <?php } ?>
                </div>
                <div class="col-md-9">
                    <?php echo $this->widget('system-user-bar'); ?>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand hidden-lg hidden-md hidden-sm" href="<?php echo Pi::url($this->url('home')); ?>"><?php echo _escape($sitename); ?></a>
                </div>
                <div class="navbar-collapse collapse">
                    <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                </div>
            </div>
        </nav>
    </div>
    <?php if ($module == 'system') { ?>
        <div class="pi-header-system hidden-xs">
            <?php echo $this->widget('widget-highlights'); ?>
        </div>
        <script type="text/javascript">
            $(document).ready(function() {
                $('.carousel').carousel({interval: 7000});
            });
        </script>
    <?php } ?>
    <div class="pi-header-body">
        <div class="pi-header-pinkbar">
            <div class="container">
                <div class="row">
                    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                        <?php echo $this->widget('search-search'); ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="pi-header-pinkbar-maintext">ما در سفرهایمان هیچ چیز به جای نمی گذاریم جز رد پا، هیچ چیز نمیکشیم جز زمان ، هیچ چیز به ارمغان نمی آوریم جز خاطرات <br /> و حفظ محیط زیست را سر لوحه سفرمان قرار میدهیم </div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 pi-header-pinkbar-box">
                        <div class="about-icon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <div class="about-title">برگزاری تور</div>
                        <p class="about-p">یادمان برگزار کننده تور های کوهنوردی و طبیعت گردی</p>
                        <div class="clearfix">&nbsp;</div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 pi-header-pinkbar-box">
                        <div class="about-icon">
                            <i class="fa fa-camera"></i>
                        </div>
                        <div class="about-title">بهترین خاطرات</div>
                        <p class="about-p">با هم دیگر بهترین خاطرات سفر را رقم می زنیم</p>
                        <div class="clearfix"> &nbsp;</div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 pi-header-pinkbar-box">
                        <div class="about-icon">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="about-title">تجربه جدید</div>
                        <p class="about-p">لذت تجربه های جدید در سفر و گشت گذار در طبیعت</p>
                        <div class="clearfix">&nbsp;</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<section class="pi-section">
    <div class="container">
        <div class="pi-main-container">
            <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
            <!-- Flash messenger -->
            <?php include $this->template('flash-messenger'); ?>
            <div class="row">
                <!-- Top head zone -->
                <?php if (!empty($blocks['0'])) { ?>
                    <div class="pi-zone-0 col-md-12">
                        <?php foreach ($blocks['0'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <!-- Left zone -->
                <?php if (!empty($blocks['1'])) { ?>
                    <div class="pi-zone-1 col-md-4">
                        <?php foreach ($blocks['1'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-md-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-md-8';
                } else {
                    echo 'col-md-12';
                }
                ?>">
                    <!-- Center top zone -->
                    <?php if (isset($blocks['2'])) { ?>
                        <div class="pi-zone-2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-3">
                                <?php
                                if (isset($blocks['3'])) {
                                    foreach ($blocks['3'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-4">
                                <?php
                                if (isset($blocks['4'])) {
                                    foreach ($blocks['4'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Module content starts -->
                    <?php if (!empty($content)) { ?>
                        <div class="<?php echo $module; ?>">
                            <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                <?php echo $content; ?>
                            </div>
                            <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                        </div>
                    <?php } ?>
                    <!-- Module content ends -->
                    <?php if (isset($blocks['5']) || isset($blocks['6']) || isset($blocks['7'])) { ?>
                        <div class="row">
                            <div class="col-md-4 pi-zone-5">
                                <?php
                                if (isset($blocks['5'])) {
                                    foreach ($blocks['5'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-4 pi-zone-6">
                                <?php
                                if (isset($blocks['6'])) {
                                    foreach ($blocks['6'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-4 pi-zone-7">
                                <?php
                                if (isset($blocks['7'])) {
                                    foreach ($blocks['7'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <!-- Right zone -->
                <?php if (isset($blocks['8'])) { ?>
                    <div class="col-md-4 pi-zone-8">
                        <?php foreach ($blocks['8'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
            <!-- Bottom foot zone -->
            <?php if (isset($blocks['99'])) { ?>
                <div class="pi-zone-99">
                    <?php foreach ($blocks['99'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</section>
<footer class="pi-footer">
    <div class="pi-footer-body clearfix">
        <div class="container">
            <div class="row">
                <div class="clearfix">
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <h3>دسته بندی تورها</h3>
                        <ul class="list-unstyled">
                            <li>
                                <a title="همه تورها" href="<?php echo Pi::url($this->url('home')); ?>/event"><i class="fa fa-angle-left"></i> همه تورها</a>
                            </li>
                            <li>
                                <a title="تورهای طبیعت گردی" href="<?php echo Pi::url($this->url('home')); ?>/event/ecotourism"><i class="fa fa-angle-left"></i> تورهای طبیعت گردی</a>
                            </li>
                            <li>
                                <a title="تورهای کوهنوردی" href="<?php echo Pi::url($this->url('home')); ?>/event/mountaineering"><i class="fa fa-angle-left"></i> تورهای کوهنوردی</a>
                            </li>
                            <li>
                                <a title="تورهای تاریخی" href="<?php echo Pi::url($this->url('home')); ?>/event/historical"><i class="fa fa-angle-left"></i> تورهای تاریخی</a>
                            </li>
                            <li>
                                <a title="تورهای رصد" href="<?php echo Pi::url($this->url('home')); ?>/event/observation"><i class="fa fa-angle-left"></i> تورهای رصد</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <h3>سایر بخش ها</h3>
                        <ul class="list-unstyled">
                            <li>
                                <a title="نکات سفر" href="<?php echo Pi::url($this->url('home')); ?>/page/tips"><i class="fa fa-angle-left"></i> نکات سفر</a>
                            </li>
                            <li>
                                <a title="سوالات متداول" href="<?php echo Pi::url($this->url('home')); ?>/page/faq"><i class="fa fa-angle-left"></i> سوالات متداول</a>
                            </li>
                            <li>
                                <a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>/contact"><i class="fa fa-angle-left"></i> تماس با ما</a>
                            </li>
                            <li>
                                <a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>/page/about-us"><i class="fa fa-angle-left"></i> درباره ما</a>
                            </li>
                            <li>
                                <a title="شرایط و مقررات" href="<?php echo Pi::url($this->url('home')); ?>/page/term-and-condition"><i class="fa fa-angle-left"></i> شرایط و مقررات</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <h3>درباره ما</h3>
                        <p>گروه  طبیعت گردی یادمان در سالهای ابتدایی فعالیت خود از سال 1388 با کسب مجوز رسمی از فدراسیون کوهنوردی و صعودهای ورزشی ج ا ا و هیئت کوهنوردی استان تهران در دانشگاه علوم تحقیقات تهران و با همکاری کانون دانشجویی هلال احمر فعالیت های آموزشی و ورزشی خود را آغاز نموده و امروز به صورت مستقل  زیر نظر سازمان میراث فرهنگی، صنایع دستی و گردشگری به فعالیت های خود ادامه میدهد و از معدود گروه های طبیعت گردی ای می‏باشد که اکثر اعضای آن دانشجو و از دانشگاه های مختلف شهر تهران و بعضاً دیگر شهر های کشورتشکیل میدهند.</p>
                        <div class="pi-footer-social text-right">
                            <h4>شبکه های اجتماعی</h4>
                            <ul class="list-inline">
                                <li><a target="_blank" title="https://www.instagram.com/yademan_group" href="https://www.instagram.com/yademan_group"><i class="fa fa-instagram"></i></a></li>
                                <li><a target="_blank" title="https://www.telegram.me/yademan_group" href="https://www.telegram.me/yademan_group"><i class="fa fa-telegram"></i></a></li>
                                <li><a target="_blank" title="https://www.twitter.com/yademangroup" href="https://www.twitter.com/yademangroup"><i class="fa fa-twitter-square"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright clearfix">
        <div class="container">
            <div class="row">
                <div class="text-left col-md-6" data-rel="license">تمام حقوق مطالب برای وب سایت <a href="<?php echo Pi::url($this->url('home')); ?>/" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="text-right col-md-6" data-rel="license">طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>